### ISSUE TITLE
jekyll-target-blank incompatible

### ISSUE THREAD

**Issue by jhil** [minimill/project-template#20]
Any idea why this plugin doesn't work? https://github.com/keithmifsud/jekyll-target-blank

**Comment by schlosser** [comment]
WDYM by "doesn't work"? Like no errors are thrown and it just doesn't add them? Or is there an error message? You followed all of the [installation steps](https://github.com/keithmifsud/jekyll-target-blank#installation?

**Comment by jhil** [comment]
Hmm, I'm not quite sure. Definitely installed it correctly. Does this mean anything to you?

```
/Users/jhil/.rbenv/versions/2.7.1/lib/ruby/2.7.0/uri/rfc3986_parser.rb:18:in `rescue in split': bad URI(is not URI?): nil (URI::InvalidURIError)
[23:27:05] 'jekyll:build' errored after 1.74 s
[23:27:05] Error: 1
    at formatError (/Users/jhil/.config/yarn/global/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (/Users/jhil/.config/yarn/global/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (events.js:326:22)
    at Gulp.EventEmitter.emit (domain.js:486:12)
    at Object.error (/Users/jhil/code/jhilco-2021/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/jhil/code/jhilco-2021/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/jhil/code/jhilco-2021/node_modules/once/once.js:25:25)
    at f (/Users/jhil/code/jhilco-2021/node_modules/once/once.js:25:25)
    at tryCatch (/Users/jhil/code/jhilco-2021/node_modules/async-done/index.js:24:15)
    at ChildProcess.done (/Users/jhil/code/jhilco-2021/node_modules/async-done/index.js:40:12)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:548:15)
    at maybeClose (internal/child_process.js:1047:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
    at Process.callbackTrampoline (internal/async_hooks.js:129:14)
[23:27:05] 'jekyll' errored after 1.74 s
[23:27:05] 'build' errored after 3.74 s
[23:27:05] 'serve' errored after 3.74 s
```

**Comment by schlosser** [comment]
It looks like you might have an <a></a> tag that doesn't have an href
attached to it?
